more verificatiton i nCI

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -69,3 +69,22 @@ jobs:
             git diff
             exit 1
           fi
+
+  verify_gomod:
+    name: "Verify Go Modules"
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-go@v5
+
+      - name: Verify Go Modules
+        run: |
+          go mod tidy
+          DIFF=$(git diff)
+          if [ -n "$DIFF" ]; then
+            echo "::error title=STALE-GOMOD::Go Modules were out of date! Please run go mod tidy."
+            echo "Diff:"
+            echo ""
+            git diff
+            exit 1
+          fi
